const RAD_FACTOR = Math.PI / 180;

const FIRST_BUBBLE_X_POS = window.innerWidth * 0.34;
const SECOND_BUBBLE_X_POS = window.innerWidth * 0.21;
const THIRD_BUBBLE_X_POS = window.innerWidth * 0.41;

const FIRST_BUBBLE_MAX_SHIFT = 75;
const SECOND_BUBBLE_MAX_SHIFT = 45;
const THIRD_BUBBLE_MAX_SHIFT = 90;

const FIRST_BUBBLE_RADIUS = 55.0;
const SECOND_BUBBLE_RADIUS = 40.0;
const THIRD_BUBBLE_RADIUS = 35.0;

const FIRST_BUBBLE_DELAY = 0;
const SECOND_BUBBLE_DELAY = 700;
const THIRD_BUBBLE_DELAY = 1000;

export {
  RAD_FACTOR,
  FIRST_BUBBLE_X_POS, SECOND_BUBBLE_X_POS, THIRD_BUBBLE_X_POS,
  FIRST_BUBBLE_MAX_SHIFT, SECOND_BUBBLE_MAX_SHIFT, THIRD_BUBBLE_MAX_SHIFT,
  FIRST_BUBBLE_RADIUS, SECOND_BUBBLE_RADIUS, THIRD_BUBBLE_RADIUS,
  FIRST_BUBBLE_DELAY, SECOND_BUBBLE_DELAY, THIRD_BUBBLE_DELAY
};
